[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[[redirects]]
  from = "/api/cap/*"
  to = "/.netlify/functions/cap-proxy/:splat"
  status = 200 
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 